name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Changez 'main' par 'master' si c'est votre branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Indiquez le dossier de votre site (ex: './dist' ou './build' si vous compilez)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
